### ISSUE TITLE
Avoid "Cannot read property 'length' of undefined" message

### ISSUE THREAD

**Issue by jvorcak** [angular-ui/ui-calendar#124]
Hi,

I've installed a plugin according to the docs and I got "Cannot read property 'length' of undefined" message in the console '(http://localhost:9000/bower_components/angular-ui-calendar/src/calendar.js:54:41)'

I guess it would be good to mention in the documentation, that you should define the eventSources somewhere in the controller before using this directive.

$scope.eventSources = [];

**Comment by acejohn** [comment]
Thank you it helps me to find out my problem =)

**Comment by equero** [comment]
I preffer to use ng-if="eventSources", inside the element.

The element will reload the DOM when the eventSources is loaded

**Comment by KatzOdeya** [comment]
Thanks, it helped me.

**Comment by qburst-hrishikesh** [comment]
Im trying to use the ui calendar with a minimal setup

`function wrapperController($scope) {`
 ` $scope.uiConfig = {`
    `calendar:{`
     ` height: 450,`
      `header:{`
        `left: 'title',`
        `center: '',`
       ` right: 'today,prev,next'`
      `}`
    `}`
  `};`
  `$scope.events = [{title: 'Event1',start: '2014-07-19'},{title: 'Event2',start: '2011-07-20'}];`
 ` $scope.eventSources = [$scope.events];`
`}`

I'm expecting the calendar to render here but stuck with the error 

> TypeError: Cannot read property 'length' of undefined

Am I doing anything wrong here, or do I have to add some other configuration?
Can anybody please help me out here?

**Comment by PoojaOfficial** [comment]
The list in which you have the data should be initialize. 
$scope.data = [];

Earlier, it was $scope.data = {}, therefore i was getting the error
