### ISSUE TITLE
lang support

### ISSUE THREAD

**Issue by akume** [angular-ui/ui-calendar#135]
i'm using version 2 of fullcalendar and when I set the "lang" property, only the buttons are changing to the correct language but the days and month are not changing to the language I set.  

```
$scope.uiConfig = {
    calendar: {
        lang: 'hi',
        height: 450,
        editable: true,
        header: {
            left: 'title',
            center: 'agendaDay,agendaWeek,month',
            right: 'today prev,next'
        }
    }
};

$scope.eventSources = [];
```

![image](https://cloud.githubusercontent.com/assets/494465/3812366/62f96ad8-1ca9-11e4-994b-0f712c92511c.png)

**Comment by hybridappdev** [comment]
how can i set specific month and year in config

**Comment by orhan27799** [comment]
I found the cause of the problem, the DatePicker language overrides the FullCalendar language, the datepicker was uninstalled, the problem was solved.
