### ISSUE TITLE
Issues with event rendering (they disappear if we switch with previous/next)

### ISSUE THREAD

**Issue by billyshena** [angular-ui/ui-calendar#163]
Hello everyone ! I'm encountering issues about event rendering on the calendar.

1) I'm basically just fetching some events object on a select box action => $http.get('/myEvents') => $scope.events.push(eachEventHere)
2) My events are loaded on the calendar (everything works fine at the moment)
3) If I switch week to week using prev/next and I come back to the original week on the calendar, my events are not displayed anymore.

Does anyone has a real fix for this issue?

Best regards

**Comment by VerzatileTom** [comment]
Adding 'true' fixed the problem, but another issue arise. It's showing duplicate events in my calendar.

**Comment by joshkurz** [comment]
@VerzatileTom can you open a new issue and send a plunker along with that please? I have not seen this bug yet.  Thanks. I am going to close this issue.

**Comment by rysiekblah** [comment]
it works good now but you have to use stick property for event:
stick: true

**Comment by VerzatileTom** [comment]
@joshkurz It's my silly mistake, i added the events the wrong way. I'm good now.
