### ISSUE TITLE
Impossible to use ng-inspector with ui-calendar

### ISSUE THREAD

**Issue by Milounas** [angular-ui/ui-calendar#170]
Hello,

When i try to use ng-inspector, it opens with the following error:

<error> ng-inspector.js:1093
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1093
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357
NGI.Model.Model.instance ng-inspector.js:1364
NGI.ModelMixin.ModelMixin.update ng-inspector.js:1112
Model.setValue ng-inspector.js:1323
Model ng-inspector.js:1357

To my knowledge, this is barely impossible to troubleshoot.

All i found on google is the angular-google-maps directive has the same issue (https://github.com/allenhwkim/angularjs-google-maps/issues/63)

If anyone has any idea, i am all ears,

Mehdi-Loup

**Comment by rev087** [comment]
This issue was related to ng-inspector's inability to handle circular references, not an issue with ui-calendar. The latest version of ng-inspector works correctly with the example at http://angular-ui.github.io/ui-calendar/

**Comment by joshkurz** [comment]
thanks @rev087
