### ISSUE TITLE
Changing an option resets date

### ISSUE THREAD

**Issue by floydqwz** [angular-ui/ui-calendar#183]
If an option is changed the fullcalendar date will be reset. There is a simple fix though. Just before reinitializing the calendar object, update the settings object with the current date:

scope.$watch(getOptions, function(newO,oldO){
  if (scope.calendar && scope.calendar.fullCalendar) {
    var date = scope.calendar.fullCalendar('getDate');
    options.year = date.getFullYear();
    options.month = date.getMonth();
    options.date = date.getDate();
  }

  scope.destroy();
  scope.init();
});

**Comment by joshkurz** [comment]
yeah I dont think this solution helps. This can be done in the controller purely.
