### ISSUE TITLE
Lost events when change view and day/month

### ISSUE THREAD

**Issue by bekerov** [angular-ui/ui-calendar#191]
I get events from factory $scope.calendar_events = CalEvents.query();
and then  $scope.eventSources = [$scope.calendar_events, $scope.events];

In my template 
```javascript
<div select="renderCalender('myCalendar1');">
<div class="alert-success calAlert" ng-show="alertMessage != undefined && alertMessage != ''">
<h4>{{alertMessage}}</h4>
</div>
<div class="calendar" ng-model="eventSources" calendar="myCalendar1" ui-calendar="uiConfig.calendar"></div>
</div>
```
From $scope.events events not lost, but from factory i cant see them after change calendar view or month/day

**Comment by joshkurz** [comment]
should be fixed for you.

**Comment by nigel-dewar** [comment]
This is not solved. Have same issue
