### ISSUE TITLE
how to get current month

### ISSUE THREAD

**Issue by ankitoodles** [angular-ui/ui-calendar#194]
I am using this directive,i want to fetch current month,year in my js.

Also if user clicks on next month then i want to get the month and year value in js to execute my custom logic.

I have added 

ui-calendar="uiConfig.calendar" calendar="myCalendar1" class="span8 calendar" ng-model="eventSources"

but myCalendar1 is not available in my controller scope.

**Comment by avastamin** [comment]
$scope.calendarConfig = {
        calendar: {
            allDaySlot: false,
            timezone: 'local',
            editable: true,
            lang: 'de',
            eventOrder: "-title",
            height: 650,
            header: {
                left:   'title',
                center: 'Custom text',
                right:  'today prev,next'
            },
            eventClick: $scope.eventClick,
            eventResizeStop: $scope.alertResize,
            eventDragStop: $scope.alertDrag,
            eventRender: $scope.eventRender,
            dayClick: $scope.dayClick
        }
    };

 <div id="medi_calendar" class="calendar" ng-model="eventSources" calendar="medi_calendar" ui-calendar="calendarConfig.calendar"></div>

I tried to get uiCalendarConfig.calendars.medi_calendar but getting error uiCalendarConfig not configured.
