### ISSUE TITLE
uiCalendarConfig.calendars is undefined

### ISSUE THREAD

**Issue by jonaswindey** [angular-ui/ui-calendar#195]
When trying to run the demo, I get:
undefined is not an object (evaluating 'uiCalendarConfig.calendars[calendar]')

Tried with both fullcalendar 2.1.1 (as in bower's depencency), or the newest (2.2.3)

**Comment by shenlong** [comment]
@jonaswindey gives us the fixed. Just go to the github and copy calendar.js and replace it to bower_components\angular-ui-calendar\src

Apparently, bower is not updated with the latest fix.
Cheers.

**Comment by bixibu** [comment]
+1 for this issue.

Manually patching it isn't a solution for me though. Will wait for a bower update.

**Comment by monkeymonk** [comment]
+1

**Comment by elropero** [comment]
+1

**Comment by couda** [comment]
+1

**Comment by monkeymonk** [comment]
As a workaround, I find **somewhere** (...you know Google) an answer to access the Fullcalendar object, even when working with the `controllerAs` syntax. The answer: `$scope` !

#### Example:
```html
<div ng-controller="ScheduleController as schedule">
    <div ui-calendar="schedule.config.calendar" calendar="calendar" ng-model="schedule.eventSources"></div>
</div>
```

```javascript
angular.module('schedule', ['ui.calendar'])
.controller('ScheduleController', ScheduleController);

function ScheduleController($scope, $timeout, uiCalendarConfig) {
    this.config = {...};
    this.eventSources = [{...}];

    // ʕ•ᴥ•ʔ <( ... )

    $timeout(function () {
        // ᕕ( ᐛ )ᕗ <( Yippee! )
        $scope.calendar.fullcalendar('render');
    });
}
```

Hope that helps!

**Comment by Reidsy** [comment]
As an alternative workaround, instead of patching calendar.js you can include the git repository and commit id in your bower.json dependencies. Adding the following line in dependencies solved the issue for me:

```
"angular-ui-calendar": "https://github.com/angular-ui/ui-calendar.git#81069d1945bea8ad1727cf5f44096f58d872a96b"
```

**Comment by jbeynar** [comment]
+1

thanks @Reidsy that works with uiCalendarConfig object !

**Comment by rlamirand** [comment]
Still having an issue with this after copying in the latest calendar.js with 289 lines.  My error is:

TypeError: undefined is not a function
    at Scope.link.scope.init (calendar.js:245)
    at Object.fn (calendar.js:285)
    at Scope.$get.Scope.$digest (angular.js:12650)
    at Scope.scopePrototype.$digest (hint.js:1468)
    at Scope.$get.Scope.$apply (angular.js:12915)
    at Scope.scopePrototype.$apply (hint.js:1478)
    at done (angular.js:8450)
    at completeRequest (angular.js:8664)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8603)

Any ideas?

**Comment by miljank** [comment]
I'm experiencing somewhat similar problems even with the latest calendar.js.

```html
<div id="calendar" ui-calendar="uiConfig.calendar" ng-model="myEvents" calendar="myCalendar"></div>
```

```javascript
console.log(uiCalendarConfig);
console.log(uiCalendarConfig.calendars);
```

Gives:

```javascript
Object {calendars: {myCalendar: n.fn.init[1] ...
Object {}
```

So `uiCalendarConfig.calendars.myCalendar` is there, but only if I dump uiCalendarConfig content. If I try to access it or `uiCalendarConfig.calendars` directly it becomes undefined. Any ideas?

**Comment by maheshkaranjkar** [comment]
I was experiencing same issue @Reidsy sollution worked for me ...
Thanks

**Comment by diosney** [comment]
Bump.

Almost six months have been passed now and still there is no clean fix to this issue (the bower update way) 

:(

**Comment by joshkurz** [comment]
turn that frown upside down. Should be good now. :)

On Fri, May 8, 2015 at 9:47 AM, Diosney Sarmiento <notifications@github.com>
wrote:

> Bump.
>
> Almost six months have been passed now and still there is no clean fix to
> this issue (the bower update way)
>
> :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ui-calendar/issues/195#issuecomment-100238099>
> .
>



-- 
*Josh Kurz*
www.joshkurz.net

**Comment by diosney** [comment]
I tested it and it grabbed the 1.0 version, which is already ok.

Thanks :)

**Comment by dalibenali** [comment]
Hi, i want display in calendar view many json objects from my rest api :
[[{"id":1,"title":"Event 1","start":"2015-09-01","_id":1},{"id":1,"title":"JPO","start":"2015-08-08","_id":2},{"id":2,"title":"Réunion","start":"2015-08-10","_id":3}]]

my broblem : I can display this static json objects fron my controller in the calendar, but when I called my rest api to retrieve the json events they no longer appear in the calendar.

controller: 
eventController.controller('EventCtrl', ['$scope', '$compile', 'UserService', 'GetEventsByUserId', 
           function($scope,$compile,UserService,GetEventsByUserId) {
	
        $scope.renderCalendar = true;
	$scope.eventSources = [];
	
    // static object for test display
    $scope.events = [{
    	id: 1,
        title: 'Event 1',
        start: "2015-09-01"
        
    }];

    //$scope.eventSources = [$scope.events];

    $scope.alertEvent = function (event, jsEvent, ui, view) {
        
        $timeout(function() {
        var sEvent = findCalendarEvent(event);
        sEvent.start = event.start.toDate();
        //sEvent.end = event.end.toDate();
        // by making this dirty we tell uiCalendar to not send updates
        // to fullCalendar.
        //sEvent.isDirty = true;
        });
    };
    
    
    // callback on resize
    $scope.alertResize = function(){
    	alert('resize !');
    };
    // callback on drag & drop
    $scope.alertDrag = function(){
    	alert('Drag !');
    };
    
    $scope.calendarConfig = {
        calendar: {
            allDaySlot: false,
            height: 450,
            //defaultView: 'agendaWeek',
            timezone: 'local',
            editable: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            eventResizeStop: $scope.alertResize,
            eventDragStop: $scope.alertDrag,
            eventRender: $scope.eventRender
        }
    };
    
    
    var user = UserService.getCurrentUser();
    var userId = user.details.id; 
    alert(userId);
    
    GetEventsByUserId.query({'id':userId}).$promise.then(function(data) {
    	angular.forEach(data,function(event,key){
			$scope.events.push({id: event.id, title: event.name, start:        moment(event.createdAt).format("YYYY-MM-DD")});
		});
		console.log(data);
		
    });
    $scope.eventSources = [$scope.events];
}]);


and in my view calendar : 
<div ui-calendar="calendarConfig.calendar" class="span8 calendar" ng-model="eventSources"></div>

think's ;)

**Comment by hybridappdev** [comment]
how i can set initial month and year in ui-calander

**Comment by olefrank** [comment]
This works for me (ui-calendar v1.0.2):

**HTML:**
```
<div ui-calendar="uiConfig.calendar" calendar="myCalendar" data-ng-model="eventSources"></div>
```

**Controller:**
```
uiCalendarConfig.calendars.myCalendar.fullCalendar('rerenderEvents');
```

**Comment by holger-dev** [comment]
For me it does not..any ideas?
Controller:
`uiCalendarConfig.calendars.calendar.fullCalendar('rerenderEvents');`
HTML:
`<div ui-calendar="uiConfig.calendar" calendar="calendar" ng-model="eventSources"></div>`

**Comment by lubochka** [comment]
When using ui-calendar edited events are not updated.
There is a bug in fullCalendar.js
in function filterLegacyEventInstances
fix from
return legacyEventInstance.id == legacyQuery;

to
return legacyEventInstance._id == legacyQuery;
