### ISSUE TITLE
Error due to source fingerprint

### ISSUE THREAD

**Issue by deepakmani** [angular-ui/ui-calendar#196]
Hi there,

Thanks a lot for the angular directive. This calendar is great.

I was using your code and noticed this error in cosole.log:

'TypeError: Cannot read property __ of undefined'
from line 48 in calendar.js

```
this.sourcesFingerprint = function(source) {
   return source.__id || (source.__id = sourceSerialId++);
}
```

The calendar seems to render fine.
Can you let me know where to look.

Thanks,
Deepak

**Comment by diegogaulke** [comment]
Great!
I just removed one undefined event and the error got away.
Helped me a lot!

**Comment by mdrubaiyat** [comment]
for angular.js having same error message...what to do
