### ISSUE TITLE
Dynamically refresh the calendar

### ISSUE THREAD

**Issue by HRK44** [angular-ui/ui-calendar#200]
Hi,

I have an issue for refreshing the calendar when I change my event data.

Here is my code.

Controller :

```
$scope.eventsF = function (start, end, bool, callback) {
   // getting the events and feeding the calendar
}

$scope.me.eventSources = [$scope.eventsF];

```

HTML :

```
<div ui-calendar="uiConfig.calendar" class="span8 calendar" id="calendar" ng-model="me.eventSources" calendar="scheduleCalendar"></div>
```

I tried to reset the $scope.me.eventSources, tried to call $scope.scheduleCalendar.fullCalendar('refresh') and so on ... nothing works.

Basically I have a dropdown input that triggers a function which should update the calendar.

Any ideas?

Thanks.

**Comment by chris-rock** [comment]
I changed scope.init:

```javascript
scope.init = function(){
    calendar.fullCalendar(options);
    window.calendar = calendar;
};
```

Afterwards I call `window.calendar.fullCalendar('refetchEvents');``

A bit hackish...

**Comment by HRK44** [comment]
Thanks for your answer but it still doesn't work for me.

When I log ```uiCalendarConfig```, I have : 
```
Object {calendars: Object}
>   calendars: Object
>      scheduleCalendar: n.fn.init[1]
```
But then, when I log ```uiCalendarConfig.calendars```, I get an empty Object {}. Very strange behaviour...

So now I access the calendar using :
```
angular.element('#calendar').fullCalendar('refetchEvents');
```
And I get the error :
```
Cannot read property 'clone' of null
    at _fetchEventSource (http://localhost:2600/lib/fullcalendar/fullcalendar.js:1433:16)
```

**Comment by chris-rock** [comment]
thats why i changes the calendar.js init function

**Comment by juristr** [comment]
I did it like this which worked perfectly:

```html
<div ui-calendar="vm.uiConfig.calendar" class="span8 calendar" ng-model="vm.eventSources" calendar="calendar"></div>
```

And in my controller

```javascript
function LogbookCtrl($log, $scope,$compile, uiCalendarConfig) {
   ...
   $scope.calendar.fullCalendar('refetchEvents');
}
```

The only thing I don't really like is that you have to inject `$scope` as it doesn't seem to work with the "controllerAs" approach (or I'm missing something).

**Comment by HRK44** [comment]
It actually worked for me. I had a race effect issue with my main data source : the calendar was updating before I have my whole data. 

I just used a $rootScope emit events to update the calendar when I have the data.

**Comment by NPM13** [comment]
Hi i am using `calendar` to fetch the event  and its coming good
 ```
<div class="calendar" ng-model="eventSources" id="calendar" calendar="myCalendar" config="uiConfig.calendar" ui-calendar="uiConfig.calendar"></div>
```
now when i am trying to delete the event using remove its deletes the event but in the `calendar` but it still doesn't show the udpate event i tried using 
```
$scope.calendar.fullCalendar('refetchEvents');
calendar.fullCalendar('refetchEvents');
````

it just throws error:
```
TypeError: Cannot read property 'fullCalendar' of undefined
```
controller
````
$scope.deleteMeal = function(list, calendar){
          $scope.remove(list);
};

$scope.remove = function(list, calendar) {
        $ionicLoading.show({template: '<i class="icon ion-loading-c"></i>'});
        //$scope.events.splice(0);
        var requestContent = $.param({
            api_token: $localStorage.accessToken,
            meal_id : list.id,
        });
        var req = {
            method: 'DELETE',
            url: link +'meal/calendar?api_token='+$localStorage.accessToken+'&meal_id='+list.id+'&id=',
            headers: {'Content-Type': 'application/x-www-form-urlencoded'}
        }
        $http(req).success(function(data) {
            $scope.mealist.splice($scope.mealist.indexOf(list), 1);
            $scope.events.splice($scope.events.indexOf(list), 1);
            calendar.fullCalendar('refetchEvents');
            $ionicLoading.hide();
        }).error(function(data) {
            console.log(data.message);
            $ionicLoading.hide();
        });
    };
```
am i doing it wrong or is it a bug?

**Comment by NPM13** [comment]
@HRK44  is it possible to  share your code in `Plunker`

**Comment by HRK44** [comment]
I don't think we have the same problem, but this is the code I'm using :

This is in the calendar controller
```
    $scope.me = this;
    $scope.me.eventSources = [$scope.eventsF];

    $rootScope.$on('updateCalendar', function () {
            window.calendar.fullCalendar('refetchEvents');
    });
```

This is in my event controller (when I get them) 
```
$scope.getSchedule = function () {
               $scope.mySchedules = [];
               console.log('starting getting schedule');
               Schedule.get({ id: $scope.eventTemplate.ScheduleId }, function (schedule) {                 
                    $scope.mySchedules .push(schedule);
                    $rootScope.$emit('updateCalendar');
              });           
        }
```
The variable $scope.mySchedules is used in the function $scope.eventsF to feed the eventSources

**Comment by goariel10** [comment]
i use this line to refresh events,

uiCalendarConfig.calendars['sorteos'].fullCalendar('refetchEvents');

**Comment by felipecaparelli** [comment]
I've tried all of those sollutions, but none of them resolved my problem. I am includind an event in another view and after that I change back, but the calendar doesn't have the new event. Follow my code:

$scope.saveActivity = function (activity) {
    //calling the service
    ActivityService.saveActivity(activity).success(function(data) {
      //adding the event to the calendar...
      $scope.events.push(data);
      //trying to update the calendar...
      uiCalendarConfig.calendars.cal.fullCalendar('rerenderEvents');
      //changing the view (back)
      $state.go('tab.home');
    }).error(function(data) {
        $ionicLoading.hide();
    });
  };

What is wrong?

**Comment by shenlong** [comment]
Wrong way of calling the calendar:

    uiCalendarConfig.calendars.cal.fullCalendar('rerenderEvents');

You should use:

    uiCalendarConfig.calendars['myCalendar'].fullCalendar('rerenderEvents');

Where 'myCalendar' refers to the calendar defined in the html:

    <div id="calendar" calendar="myCalendar"
                 ui-calendar="calendarOptions.calendar" ng-model="eventSources"></div>

**Comment by papiermache** [comment]
Similar problem: am using angular-ui tabs, fullCalendar is in 1st tab. When another tab is open, data saving raises an event.  Calendar controller has a $on for the event, then calls refetchEvents.  log shows request is sent and data comes back. However when tabbing back to 1st tab, the calendar is empty. Any thoughts appreciated, this is killing me.

**Comment by felipecaparelli** [comment]
Hi papiermache,

I fixed my problem using 2 steps:

1 - Ionic view.render listener to load my calendar code:

*$scope.$on('$ionicView.enter', function() { //put your code inside this
block (with step 2)! }*

2 - check if DOM is ready:

*ionic.DomUtil.ready(function(){*
*        uiCalendarConfig.calendars['cal'].fullCalendar('changeView',
'month');       *
*});*

Cheers,

Felipe Caparelli

**Comment by blaskovicz** [comment]
Calling `$scope.myCalendar.fullCalendar("refetchEvents")` did the trick for me.

_Note:_ In order to get access to `$scope.myCalendar`, I added `calendar="myCalendar"` to my `ui-calendar` div.

**Comment by adithyasai** [comment]
If suppose i have two two calendars and the first one with `calendar="myCalendarOne"` and the second one with `calendar="myCalendarTwo"` 
when i tried to observe the uiCalendarConfig.calendars in console i can only observe single object i.e.. "myCalendarOne" i am unable to see myCalendarTwo.
I want to change the view of "myCalendarTwo" when my first calendar(myCalendarOne) changes.

so need to do something like this:
`uiCalendarConfig.calendars['myCalendarTwo'].fullCalendar('gotoDate', date);`

I have tried in different ways. but couldn't get that. Please suggest some way to do that

**Comment by jdmagic21** [comment]
@chris-rock Cannot read property fullcalendar of undefined.

**Comment by jdmagic21** [comment]
@juristr  Cannot read property fullcalendar of undefined.

**Comment by jdmagic21** [comment]
Why are you guys talking about Ionic when this is clearly an Angular issue? Also, if fullcalendar is undefined how is this supposed to work. Please be more specific in your answers.

**Comment by olefrank** [comment]
I solved it by using $timeout. When I add a new event (in my controller), I rerender like this:

```
$timeout(function() {
    uiCalendarConfig.calendars.myCalendar.fullCalendar('rerenderEvents');
});
```

```html
<div ui-calendar="uiConfig.calendar" calendar="myCalendar" data-ng-model="eventSources"></div>
```

**Comment by lubochka** [comment]
When using ui-calendar edited events are not updated.
There is a bug in fullCalendar.js
in function filterLegacyEventInstances
fix from
return legacyEventInstance.id == legacyQuery;

to
return legacyEventInstance._id == legacyQuery;

**Comment by felipecaparelli** [comment]
*|SUBJECT|*    *|MC_PREVIEW_TEXT|* <http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiQ2MwQ3BRdjVrbThtV0ljRkNwdzFCMFp4VzNjIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cIixcImlkXCI6XCI3YmQ0YzBiMDg1ZmM0NmFkODRhNWI5Y2I5NDAyYmZlMVwiLFwidXJsX2lkc1wiOltcImQ1Njg3MTlmM2JiMDlkYzZkMWYyZGYxYTIxNTZkZmFiNDU0OTUyZDRcIl19In0>      
                                     <http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiQ2MwQ3BRdjVrbThtV0ljRkNwdzFCMFp4VzNjIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cIixcImlkXCI6XCI3YmQ0YzBiMDg1ZmM0NmFkODRhNWI5Y2I5NDAyYmZlMVwiLFwidXJsX2lkc1wiOltcImQ1Njg3MTlmM2JiMDlkYzZkMWYyZGYxYTIxNTZkZmFiNDU0OTUyZDRcIl19In0>          
   Felipe Gabriel Caparelli sent you a free  international money transfer. 
             Send money to 60 countries at the lowest possible fee, with
the real exchange rate. 
                     Claim your free transfer now
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiQzdlSjdNQktSakZyRlVld0tsb09qUU5PUTlZIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvZVxcXC9mZWxpcGVjMjc3P2VtYWlsPXJlcGx5JTJCMDAxMzNmMjdiY2JkMzg4MGVjY2FiNGI2NjBjN2JiNjM3YmFkMDNhZWZkNzBkZTNhOTJjZjAwMDAwMDAxMTI4Yzc1MDQ5MmExNjljZTAzMWJjMjU5JTQwcmVwbHkuZ2l0aHViLmNvbSZhbXA7dXRtX2NvbnRlbnQ9djMtc2hvcnRcIixcImlkXCI6XCI3YmQ0YzBiMDg1ZmM0NmFkODRhNWI5Y2I5NDAyYmZlMVwiLFwidXJsX2lkc1wiOltcIjgxODIyMWFiNjBiZWY1MWFjYzI3NDAzNGY1YWI1ZDk5ZGYwNTk0OTJcIl19In0>

                                           Got questions? Read our FAQs
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiei1BNVpYSkJyZ0VzcmJqQ0VFYUxtaTNsUV9JIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvaGVscFwiLFwiaWRcIjpcIjdiZDRjMGIwODVmYzQ2YWQ4NGE1YjljYjk0MDJiZmUxXCIsXCJ1cmxfaWRzXCI6W1wiZjUyOTA1NGQ2YzUxNThlMTJlYzU0ZTFiZjJlODNiOTA4ODZhZGUyNVwiXX0ifQ> Need to get in touch?  Reply to this
email <mailto:support@transferwise.com> Not interested? go here
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiUHZFZ2RDaXRKakhjYjlIZmhfdjhnRlJnQk00IiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvcmVmZXJyYWxcXFwvdW5zdWJzY3JpYmU_ZW1haWw9cmVwbHklMkIwMDEzM2YyN2JjYmQzODgwZWNjYWI0YjY2MGM3YmI2MzdiYWQwM2FlZmQ3MGRlM2E5MmNmMDAwMDAwMDExMjhjNzUwNDkyYTE2OWNlMDMxYmMyNTklNDByZXBseS5naXRodWIuY29tXCIsXCJpZFwiOlwiN2JkNGMwYjA4NWZjNDZhZDg0YTViOWNiOTQwMmJmZTFcIixcInVybF9pZHNcIjpbXCI4MTgyMjFhYjYwYmVmNTFhY2MyNzQwMzRmNWFiNWQ5OWRmMDU5NDkyXCJdfSJ9>.
    TransferWise Limited is a company registered in England and Wales with
registered number 07209813. Our registered office is at 6th Floor, The Tea
Building, 56 Shoreditch High Street, London, E1 6JJ. We are an Electronic
Money Institution authorised by the Financial Conduct Authority with firm
reference 900507.

**Comment by codedcontainer** [comment]
@felipecaparelli Really?

**Comment by felipecaparelli** [comment]
Sorry @jdmagic21 ... this email was in my personal mail list... my mistake!

**Comment by felipecaparelli** [comment]
*|SUBJECT|*    *|MC_PREVIEW_TEXT|* <http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiNmdVUC1idDBQeFRPd3RHOGk2ZjVKV21CdU5JIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cIixcImlkXCI6XCI3Njg3ZTY3ZWEzYWQ0NTQxOThiYmNmOWY2ZmVkNjczMlwiLFwidXJsX2lkc1wiOltcImQ1Njg3MTlmM2JiMDlkYzZkMWYyZGYxYTIxNTZkZmFiNDU0OTUyZDRcIl19In0>      
                                     <http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoiNmdVUC1idDBQeFRPd3RHOGk2ZjVKV21CdU5JIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cIixcImlkXCI6XCI3Njg3ZTY3ZWEzYWQ0NTQxOThiYmNmOWY2ZmVkNjczMlwiLFwidXJsX2lkc1wiOltcImQ1Njg3MTlmM2JiMDlkYzZkMWYyZGYxYTIxNTZkZmFiNDU0OTUyZDRcIl19In0>          
   Don't forget! You have a free  international money transfer from Felipe
Gabriel Caparelli. 
             Send money to 60 countries at the lowest possible fee, with
the real exchange rate. 
                     Claim your free transfer now
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoieTJTeW5Ral9rTUEtUHZJV1JwVjNpTThxX1N3IiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvZVxcXC9mZWxpcGVjMjc3P2VtYWlsPXJlcGx5JTJCMDAxMzNmMjdiY2JkMzg4MGVjY2FiNGI2NjBjN2JiNjM3YmFkMDNhZWZkNzBkZTNhOTJjZjAwMDAwMDAxMTI4Yzc1MDQ5MmExNjljZTAzMWJjMjU5JTQwcmVwbHkuZ2l0aHViLmNvbSZhbXA7dXRtX2NvbnRlbnQ9djMtc2hvcnQtcmVtaW5kZXJcIixcImlkXCI6XCI3Njg3ZTY3ZWEzYWQ0NTQxOThiYmNmOWY2ZmVkNjczMlwiLFwidXJsX2lkc1wiOltcIjgxODIyMWFiNjBiZWY1MWFjYzI3NDAzNGY1YWI1ZDk5ZGYwNTk0OTJcIl19In0>

                                           Got questions? Read our FAQs
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoicjdXV1lLU0VHWDFaTkNNTEp1d1hiV281Sjc0IiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvaGVscFwiLFwiaWRcIjpcIjc2ODdlNjdlYTNhZDQ1NDE5OGJiY2Y5ZjZmZWQ2NzMyXCIsXCJ1cmxfaWRzXCI6W1wiZjUyOTA1NGQ2YzUxNThlMTJlYzU0ZTFiZjJlODNiOTA4ODZhZGUyNVwiXX0ifQ> Need to get in touch?  Reply to this
email <mailto:support@transferwise.com> Not interested? go here
<http://links.transferwise.com/track/click/30074347/transferwise.com?p=eyJzIjoieUhhbXpvTFpoMUJiVkFBUWw2MFdhenhVZ3lzIiwidiI6MSwicCI6IntcInVcIjozMDA3NDM0NyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYW5zZmVyd2lzZS5jb21cXFwvcmVmZXJyYWxcXFwvdW5zdWJzY3JpYmU_ZW1haWw9cmVwbHklMkIwMDEzM2YyN2JjYmQzODgwZWNjYWI0YjY2MGM3YmI2MzdiYWQwM2FlZmQ3MGRlM2E5MmNmMDAwMDAwMDExMjhjNzUwNDkyYTE2OWNlMDMxYmMyNTklNDByZXBseS5naXRodWIuY29tXCIsXCJpZFwiOlwiNzY4N2U2N2VhM2FkNDU0MTk4YmJjZjlmNmZlZDY3MzJcIixcInVybF9pZHNcIjpbXCI4MTgyMjFhYjYwYmVmNTFhY2MyNzQwMzRmNWFiNWQ5OWRmMDU5NDkyXCJdfSJ9>.
    TransferWise Limited is a company registered in England and Wales with
registered number 07209813. Our registered office is at 6th Floor, The Tea
Building, 56 Shoreditch High Street, London, E1 6JJ. We are an Electronic
Money Institution authorised by the Financial Conduct Authority with firm
reference 900507.

**Comment by cassmtnr** [comment]
@felipecaparelli delete your last comment please
