### ISSUE TITLE
Event constraints not working

### ISSUE THREAD

**Issue by emertechie** [angular-ui/ui-calendar#204]
(Using 0.9.0-beta.1)

If I use the events constraint with the raw FullCalendar object then they behave correctly. When bound via ng-model, they don't seem to work.

Demo: http://jsfiddle.net/emertechie/fECuY/35/

You should be able to drag the event anywhere in the green 'available' area but as you'll see you can't. Switch to using the 2 lines I point out in the fiddle and things work.

**Comment by getsetbro** [comment]
+1

**Comment by joshkurz** [comment]
I cannot reproduce this. Is it still a bug in the latest master?

**Comment by getsetbro** [comment]
I was able to make it work.

**Comment by joshkurz** [comment]
awesome

**Comment by getsetbro** [comment]
Actually I wasn't able to make it work as @emertechie stated "When bound via ng-model, they don't seem to work."
I was only able to make it work "If I use the events constraint with the raw FullCalendar object then they behave correctly."

**Comment by getsetbro** [comment]
Closest I could come was to put the constraints in the $scope.uiConfig.events
http://jsfiddle.net/getsetbro/fECuY/57/

**Comment by an-tk** [comment]
It is still impossible to set event.constraint via ng-model in the latest directive version.
http://jsfiddle.net/antk/cbs202vr
