### ISSUE TITLE
windowResize only works on width and not height?

### ISSUE THREAD

**Issue by arecaps** [angular-ui/ui-calendar#214]
I want that the height of the calendar should resize after a user adjusts the window height.
I set in my configuration ``` windowResize: $scope.alertOnWindowResize``` and I have the following function:

```javascript
$scope.alertOnWindowResize = function(){

        calendarHeight = $window.innerHeight - 50;

        try {

          $scope.calendar.fullCalendar('option', 'height', calendarHeight);

        } catch(e) {

          $log.error(e);

        }

      };
```

This works fine when I change the width, but nothing happens when I change the height. Am I doing something wrong, or is this intentional?

**Comment by joshkurz** [comment]
hmm, maybe something is up with your specific js or css can you provide an example?

**Comment by arecaps** [comment]
We redid that page, so this no longer applies. You can close this issue.
