### ISSUE TITLE
New events are not displayed when eventSource is updated via $scope.$on

### ISSUE THREAD

**Issue by puruzio** [angular-ui/ui-calendar#222]
As shown in this plunkr example, a new event can be added and displayed when the event is appended to $scope.events directly. However, if I update $scope.events through factory.events, the new event is not displayed on the calendar.

http://plnkr.co/edit/BkdzJJ?p=preview

/ This is how I attempted to populate $scope.events2
$scope.$on('gDataUpdated', function(){

  $scope.events2 = gDataService.events2;
  alert('gDataService # of events =' + gDataService.events2.length.toString()  + '; $scope.events2 includes '+ $scope.events2.length.toString());
  // The alert message indicates $scope.events is properly updated based on 
  // gDataService.events2, but the new event doesn't appear on the calendar.
});

**Comment by ThomasBS** [comment]
Hi puruzio. I've had sort of the same problem. If you push the new event to the array of sources, it will work. F.x. changing your $scope.$on to:

```javascript
    // This is how I attempted to populate $scope.events2
    $scope.$on('gDataUpdated', function(){
      //alert(gDataService.events2.length);
      
      for (var i = 0; i < gDataService.events2.length; i++) {
        $scope.events2.push(gDataService.events2[i]);
      }

    });
```

**Comment by dumbguy5689** [comment]
I also had to push events onto the eventSource inside of a promise.

**Comment by joshkurz** [comment]
this can be solved very simply. There is no need to reset the array on every broadcast. Just set the $scope.events2 = service.events; and all will be well. http://plnkr.co/edit/xGPRRu?p=preview
