### ISSUE TITLE
Capture "Next / Prev" event 

### ISSUE THREAD

**Issue by alo** [angular-ui/ui-calendar#227]
Hi, 

I need to capture "next / prev month" events in my directive. 

Thx

**Comment by getsetbro** [comment]
If your reason is like mine was: to constrain events to a time period than you might find the fiddle link in this issue helpful: https://github.com/angular-ui/ui-calendar/issues/204

**Comment by shenlong** [comment]
+1
I also need this event. Apparently, I tried it over here:
http://stackoverflow.com/questions/32963104/extending-scope-function-to-directive-in-angular-1-4

But the event is not working in angular 1.4.

**Comment by akapaul** [comment]
If you need using custom function for prev/next buttons, you can use specify it in "events" field http://fullcalendar.io/docs/event_data/events_function/
