### ISSUE TITLE
Multiple classNames and events

### ISSUE THREAD

**Issue by sidonaldson** [angular-ui/ui-calendar#229]
Hi,

I have noticed that the event className is appended onto each event node twice, and that the render event fires multiple times for each event when the calendar is built. Is this deliberate or an bug? This may provide a solution to other bug people have reported.

:)

**Comment by joshkurz** [comment]
so, the reason the render event fires multiple time in our demo is because there are multiple calendars on the page. The classNames are pure fullCalendar.

**Comment by sidonaldson** [comment]
So the double classname is a bug within the dependency?

Here's a demo any way - http://output.jsbin.com/zunexu/1/
