### ISSUE TITLE
bug on new event then change month (you can see it in demo)

### ISSUE THREAD

**Issue by smetsboris** [angular-ui/ui-calendar#234]
Hi, in the demo if you had an event and then change month, the event disappear. But if you click on change lang , new event is appearing !! It seems the watcher is working for a change on the uiconfig but not on eventSources's array...

**Comment by joe-schorn** [comment]
This may be related to sticky events discussed in this issue: https://github.com/angular-ui/ui-calendar/issues/99

try @linkolen's suggestion: 

just go to your calendar.js and change onAdded
eventsWatcher.onAdded = function(event) {
scope.calendar.fullCalendar('renderEvent', event,true);
};

**Comment by smetsboris** [comment]
thanks a lot!! it did the tricks!!
