### ISSUE TITLE
Tooltips are still displayed even if the event is moved moving 

### ISSUE THREAD

**Issue by shershen08** [angular-ui/ui-calendar#237]
Tooltip that appears on the event block on hover is nice, but if you start moving event all around you'll get those tooltips-leftovers. 
Chrome 41.0

![screen shot 2015-03-09 at 16 25 32](https://cloud.githubusercontent.com/assets/1363772/6557958/588fe17e-c679-11e4-8000-78f9ce915449.png)

**Comment by joshkurz** [comment]
if you set the tooltips to the body, this works fine.
