### ISSUE TITLE
Bower version is not correct version

### ISSUE THREAD

**Issue by kenkopelson** [angular-ui/ui-calendar#249]
Bower keeps installing what it thinks is version 0.8.1, but the actual code that is currently in Bower is not that version.  After comparing the code in Bower with the code that is available through your zip download, it is quite clear that the Bower code is quite a bit behind.

Could you please update the Bower code to be the current version?  Thank you very much :)

**Comment by joshkurz** [comment]
the repo has been updated to 1.0.0
