### ISSUE TITLE
Event sources not showing in the calendar (ng1.3.15 + fullcalendar2.0)

### ISSUE THREAD

**Issue by akocmark** [angular-ui/ui-calendar#258]
Hi,

This is what I got on my view
```
<div ui-calendar="uiConfig.calendar" ng-model="eventSources"></div>
```

And on my controller
```
    $scope.uiConfig = {
      calendar:{
        editable: true,
        header:{
          left: 'month agendaWeek agendaDay',
          center: 'title',
          right: 'today prev,next'
        },
        dayClick: $scope.alertEventOnClick,
        eventDrop: $scope.alertOnDrop,
        eventResize: $scope.alertOnResize
      }
    };

    $scope.eventSources = [
        {
            title  : 'Event 1',
            start  : '2015-05-01'
        },
        {
            title  : 'Event 2',
            start  : '2015-05-05',
            end    : '2015-05-07'
        },
        {
            title  : 'Event 3',
            start  : '2015-05-09 12:30:00',
            allDay : false // will make the time show
        }
    ];

```

The calendar UI is showing but not the events, here is a screen shot of it.
![screenshot from 2015-05-04 13 11 23](https://cloud.githubusercontent.com/assets/4981864/7451212/2e815f04-f25f-11e4-91fd-30c94e7326fd.png)

What do you think was wrong? Please help! :(

**Comment by akocmark** [comment]
and also if I push an item in the eventSources array this function fires
```
        eventSourcesWatcher.onAdded = function(source) {
          console.log('add');
          scope.calendar.fullCalendar('addEventSource', source);
          sourcesChanged = true;
        };
```

i don't know what was tho.. maybe this one?
```  scope.calendar.fullCalendar('addEventSource', source);   ```

**Comment by akocmark** [comment]
it's just now that I realized that there is no support for 1.3.15

**Comment by getsetbro** [comment]
I dealing with this now. eventSources needs to be an array of arrays, not just an array.

**Comment by akocmark** [comment]
yeah, I was able to make it work with 1.3.15 by making the first item of eventSources to be an array which contains the actual events array. Thank you tho!
