### ISSUE TITLE
uiCalendarConfig. What? How?

### ISSUE THREAD

**Issue by SkyQuant** [angular-ui/ui-calendar#260]
That's a function on the main page ```function CalendarCtrl($scope,$compile,uiCalendarConfig)```
What is ```uiCalendarConfig``` and how to inject this object? Suppose I can't change a timeframe (daily / weekly / monthly),  ```ReferenceError: uiCalendarConfig is not defined``` output in console.

**Comment by SkyQuant** [comment]
Could anybody provide Visual Studio demo-version, without bower installation?

**Comment by joshkurz** [comment]
uiCalendarConfig is the global singleton config object that gets created when the calendar is initialized. If you are including ui-calendar.js then this should be available in your code. Please provide an example.
