### ISSUE TITLE
Does exist any way to have info about changing event(s) in calendar?

### ISSUE THREAD

**Issue by skeefo** [angular-ui/ui-calendar#261]
Hi, I've read readme, FC documents and source code and understood, that there is no 2-way binding between eventSources and calendar. Am I right? How is it possible to understand that calendar events were changed by user and save these changes? 
Thanks.

**Comment by joshkurz** [comment]
do you mean save to your server? This would be done on some event callback function that you have either tied to the calendars event callback system or it could/should be completely separate.

**Comment by joshkurz** [comment]
My b did not mean to close the issue. Do you have a reproduction scenario or am I misunderstanding the issue?

**Comment by skeefo** [comment]
Hi! Thank you for your answer. Yes, I mean some way to work with calendar data "angular way". So - we assign ng-model to calendar directive - eventSources, but when user changes something in calendar it does not affects on ng-model. So I can not just use $scope.$watch to check if events are changed and save current state to server. Yes, I've done finally it by callbacks and so on, but I'm pretty sure - it is not an "angular way". Probably it would be better to hide callbacks inside the directive and work with ng-model controller - https://docs.angularjs.org/api/ng/type/ngModel.NgModelController ?

**Comment by jkurz** [comment]
The callbacks are the way to communicate this with the calendar, based off of user actions. We have tied into many of the main callbacks to keep the models in sync with each other. It there is an event that you think has been left out, please let us know. I am going to close this for now though, as I don't really see an issue here.

**Comment by skeefo** [comment]
Ok, thank you for your attention.
