### ISSUE TITLE
calendar.fullCalendar is not a function 

### ISSUE THREAD

**Issue by tbowler** [angular-ui/ui-calendar#267]
When trying to use the calendar I get the following error. Any ideas?

TypeError: scope.calendar.fullCalendar is not a function
    at Scope.link.scope.init (calendar.js:191)
    at Object.fn (calendar.js:230)
    at Scope.$get.Scope.$digest (angular.js:12251)
    at Scope.$get.Scope.$apply (angular.js:12516)
    at HTMLButtonElement.<anonymous> (angular.js:18626)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4409)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (jquery.js:4095)

**Comment by joshkurz** [comment]
what version of uiCalendar are you using? We do not set calendar to the scope anymore.

**Comment by marksoenen** [comment]
The paths in the documentation are not correct.  The <script> includes need to be:

    'bower_components/jquery/dist/jquery.min.js',
    'bower_components/moment/min/moment.min.js',
    'bower_components/fullcalendar/dist/fullcalendar.min.js',
    'bower_components/fullcalendar/dist/gcal.js',
    'bower_components/angular/angular.js',
    'bower_components/angular-ui-calendar/calendar.min.js',

**Comment by marksoenen** [comment]
'bower_components/jquery/dist/jquery.min.js',
    'bower_components/moment/min/moment.min.js',
    'bower_components/fullcalendar/dist/fullcalendar.min.js',
    'bower_components/fullcalendar/dist/gcal.js',
    'bower_components/angular/angular.js',
    'bower_components/angular-ui-calendar/calendar.min.js',

**Comment by ballerabdude** [comment]
@marksoenen thanks for finding that error I will fix it

**Comment by rehanaShr09** [comment]
I am getting same error but none of solution is working for me .I have tried swaping js files step by step ,this also doesnot work for me.I cannot figure out what is exact problem in my code.
I am continuosly getting .Error: calendar.fullCalendar is not a function.Help me on this.Thanks in advance

**Comment by csabaujvari** [comment]
calendar.js
I modified scope.initCalendar function for this:
`scope.initCalendar = function () {
                    if (!calendar) {
                        calendar = $(elm);
                    }
                    calendar.fullCalendar(options);
                    if (attrs.calendar) {
                        uiCalendarConfig.calendars[attrs.calendar] = calendar;
                    }
};`
 

it works for me now.

**Comment by martinmicunda** [comment]
@joshkurz the fix provided by @csabaujvari works for me too.. Is it possible to push this fix to master and publish to npm? The current code is using `angular.element` which I believe is wrong because you should work with `jquery` object. Thanks 

```js
calendar = angular.element(elm).html('');  ---> replace this line with calendar = $(elm);
```

**Comment by martinmicunda** [comment]
@joshkurz is there plan re-open this issue and push the fix for this... ? Thanks

**Comment by sseppola** [comment]
I was getting `calendar.fullcalendar is not a function` in an Angular app I'm converting to use Webpack. The suggestion by @csabaujvari worked, however it's not ideal because it uses the `$` global instead of the `angular.element` alias. In my case I discovered that the reason I got this error was because Angular was using `jqlite` instead of `jQuery`, which was solved easily by using the [expose-loader](https://github.com/webpack/expose-loader) and loading jQuery before Angular.

**Comment by vrfox** [comment]
been trying to use Angular: ui-calendar with meteor, but get this error.

TypeError: calendar.fullCalendar is not a function
    at Scope.scope.initCalendar (calendar.js:265)
    at Object.fn (calendar.js:337)
    at Scope.$digest (angular.js:15896)
    at Scope.$apply (angular.js:16160)
    at bootstrapApply (angular.js:1679)
    at Object.invoke (angular.js:4523)
    at doBootstrap (angular.js:1677)
    at Object.bootstrap (angular.js:1697)
    at HTMLDocument.onReady (app.js:47)
    at fire (jquery.js:3143)
In meteor packages i habe:

angular 1.2.3 angularui:ui-calendar

also tried to use the package inserted directly not using meteor add. but using the calendar.js file (which is different)

Both get the same error.

Tried this: https://github.com/angular-ui/ui-calendar/issues/267

       scope.initCalendar = function () {
                if (!calendar) {
                    calendar = $(elm);
                }
                calendar.fullCalendar(options);
                if (attrs.calendar) {
                    uiCalendarConfig.calendars[attrs.calendar] = calendar;
                }
         };
But is seems this fix doesnt work with meteor and angular-meteor.

Any ideas on how to fix this issue?

**Comment by ni3aj** [comment]
i was getting same error

"calendar.fullCalendar is not a function. (In 'calendar.fullCalendar(options)', 'calendar.fullCalendar' is undefined)"

what worked for me is, loading jquery before angular. but still css is not loading well.

**Comment by fabrikate** [comment]
I am getting the same issue. I've tried all of the suggestions above. After changing my scope.initCalendar function I get a new error:
```angular.js:12520 TypeError: scope.init is not a function
    at Object.fn (calendar.js:309)
    at Scope.$digest (angular.js:15896)
    at Scope.$apply (angular.js:16160)
    at HTMLDivElement.<anonymous> (angular.js:23618)
    at HTMLDivElement.n.event.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)```

Any suggestions for fixing this?

**Comment by darkbls** [comment]
@csabaujvari works for me as well. I am using the following versions:
ui-full-calendar: v1.0.2.
angular:  v1.5.8

**Comment by nobleson** [comment]
Hello can someone help me out please.
I have added the compressed version(yui-min.js) of YUI3 library, after looking through this tutorial: http://yuilibrary.com/yui/docs/calendar/calendar-simple.html and it works fine. I tested it locally though with internet connection. Once there is no internet, the calendar refuse to display. i am testing with firefox and i checked the console and found a error log indicating that **Y.Calendar** is not a function. please i would like to know what library i should include to make the calendar work locally without internet on my system.

**Comment by asulaiman** [comment]
Really not fond of this approach for accessing the calendar. This forces devs to run angular with jquery instead of jqlite.

**Comment by stefan-dimitrov** [comment]
The error appears when using the calendar with angular v1.5.8

```
TypeError: calendar.fullCalendar is not a function
    at Scope.scope.initCalendar (calendar.js:288)
    at calendar.js:358
    at Scope.$digest (angular.js:17524)
    at Scope.$apply (angular.js:17790)
    at angular.js:19621
    at completeOutstandingRequest (angular.js:5964)
    at angular.js:6243
```

If these changes are made in `calendar.js`: 
```js
scope.destroyCalendar = function () {
    ...
    if (attrs.calendar) {
        calendar = uiCalendarConfig.calendars[attrs.calendar] = $(elm).html('');
    } else {
        calendar = $(elm).html('');
    }
};

scope.initCalendar = function () {
    if (!calendar) {
        calendar = $(elm).html('');
    }
    ...
};
```
then it works, but both `destroyCalendar` and `initCalendar` need to change their `angular.element(...)` to `$(...)`.

I saw that it is preferred to use `angular.element` over jquery - https://github.com/angular-ui/ui-calendar/commit/568e4311206de68beeac5cc2d47a9241a8247f78#commitcomment-18806502

**Comment by stefan-dimitrov** [comment]
Sorry for my slow reaction.
#460 doesn't fix the problem. A change needs to be made also in the `scope.destroyCalendar` method.

**Comment by santoshyadav198613** [comment]
Calling jquery before angular worked for me

**Comment by itanex** [comment]
I came across this issue as well. I had copied sections of the code from the documentation site. The order of the script files was all that I had to change before it started working for me. Here is the order I have:
```
  <script src="vendor/jquery/dist/jquery.min.js"></script>
  <script src="vendor/moment/min/moment.min.js"></script>
  <script src="vendor/fullcalendar/dist/fullcalendar.min.js"></script>
  <script src="vendor/fullcalendar/dist/gcal.js"></script>

  <script src="vendor/angular/angular.min.js"></script>
  <script src="vendor/angular-bootstrap/ui-bootstrap.min.js"></script>
  <script src="vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
  <script src="vendor/angular-ui-calendar/src/calendar.js"></script>

  <script src="scripts/app.js"></script>
```

My project is over on my [repo](http://github.com/itanex/ng-unemployment)

**Comment by architahluwalia** [comment]
Got the same error. However loading jquery before angular did the trick for me.

**Comment by luizhenriquesoares** [comment]
this work to me

**Comment by IshanBuddhikaSanmark** [comment]
Replace 

```javascript
if (!calendar) {
    calendar = angular.element(elm).html('');
}
```
with

```javascript
calendar = $(elm);
```
This works for me. Try it...

**Comment by GIBuddhika** [comment]
Replace

 ```javascript
 if (!calendar) {
     calendar = angular.element(elm).html('');
 }
 ```
 with

 ```javascript 
calendar = $(elm); 
```
 This works for me. Try it...

**Comment by luciantanase** [comment]
Just use once the reference of jquery.min.js in the page.  This work for me!

**Comment by daton89** [comment]
instead of replacing angular.element with $(elm) you need to check if your angular.element is a jqLite or a Jquery object... 
angular need to find jquery in `window.jQuery`to use jquery instead of jqLite.. so if you are using angular-ui-calendar with fullcalendar built on top of jquery i think this  should probably be recommended

**Comment by Rinzin2018** [comment]
TypeError: _fullcalendar_core__WEBPACK_IMPORTED_MODULE_2__.Calendar.fullCalendar is not a function

same problem with me in react js
