### ISSUE TITLE
JavaScript Errors when ui-calendar is used inside another directive

### ISSUE THREAD

**Issue by chengyin** [angular-ui/ui-calendar#27]
I'm trying to wrap `ui-calendar` inside another directive. I basically moved the working code in a ng-controller into the directive. The code worked fine in the controller, but when I include the directive instead of `ui-calendar` direct, I got the JS errors: https://gist.github.com/chengyin/5660043

I might have misused directive. If a sample code is needed, I can create it.

Thank you.

**Comment by bokes** [comment]
I had precisely the same situation, and using the pre link instead of link solved the errors.
thanks glebm
