### ISSUE TITLE
Minified version doesn't "stick" event when switching months.

### ISSUE THREAD

**Issue by willykc** [angular-ui/ui-calendar#271]
Issue reproduced in this plunker: http://plnkr.co/edit/SpB35NS9YjxobwF4HBsQ?p=preview

Steps to reproduce:
1. Add new event.
2. Switch back and forth months.

The newly added event disappears from the calendar.

When loading unminified version of ui-calendar it works fine.

**Comment by jkurz** [comment]
ok, well we should not even had that min file in the repo. so thanks. :) I removed it.

if you use the most updated minified file from master it works. This needs to be built from the command line via 'grunt minify' http://plnkr.co/edit/H9wKUTpbIONkscIRFK6A?p=preview

**Comment by willykc** [comment]
Thanks for the update!, it would still be cool to have a minified version in the Bower package though.

**Comment by aralroca** [comment]
Why the minified file was removed?
