### ISSUE TITLE
Upgrade to Fullcalendar 2.3

### ISSUE THREAD

**Issue by Sefriol** [angular-ui/ui-calendar#277]
Current version of Fullcalendar has huge problems with performance when dealing with huge amounts of events.
https://code.google.com/p/fullcalendar/issues/detail?id=2259
This has been fixed in later versions. So far, with my environment, I haven't encountered any bugs.

Atleast it would be a worth of thought.

**Comment by reggieboyYEAH** [comment]
+1

**Comment by DanDeMicco** [comment]
Is there any API changes that would be an issue in upgrading? I just installed 2.3.1 with ui-calendar and it seems to be working fine. Rendering speed seems a bit better

**Comment by reggieboyYEAH** [comment]
I'm also using v2.3.1 with ui-calendar and so far no issues. There are tons of improvements since 2.1.1 you can check it here https://github.com/arshaw/fullcalendar/blob/master/changelog.md

**Comment by Sefriol** [comment]
Performance problem with rendering might be related to scope problem discussed in other threads. Unfortunately, I don't have the time to investigate it further.

**Comment by MuratTopcu** [comment]
Please update v2.3.2.

**Comment by reggieboyYEAH** [comment]
@MuratTopcu the main branch is already using 2.3.2

**Comment by Sefriol** [comment]
Forgot to close this. Nice to see some frequent updates coming from you guys :)
