### ISSUE TITLE
calendar attribute not injecting calendar object into scope

### ISSUE THREAD

**Issue by rlrhett** [angular-ui/ui-calendar#28]
The calendar attribute is not passing the calendar object to scope.  I am getting "TypeError: Cannot call method 'fullCalendar' of undefined" when calling $scope.myCalendar.fullCalendar('render'). Code:

```
<div ng-controller="CalendarCtrl">
  <div ui-calendar="calendarOptions" ng-model="eventSources" calendar="myCalendar"></div> 
</div>

angular.module('CalendarApp')
  .controller('CalndarCtrl', function ($scope) {
    $scope.calendarOptions = {};
    $scope.eventSources = [];
    $scope.myCalendar.fullCalendar('render');
});
```

I can tell that ui-calendar="calendarOptions" and ng-model="eventSources" is mapping correctly to their respective $scope objects.  If I change their values, they are reflected in the calendar.  However, the actual calendar object is not.

Is this a bug, am I misunderstanding the ReadMe, or is there something more I need to do to inject the calendar object into the controller's scope?

**Comment by niofis** [comment]
Found a solution, modified the init function (line 244) :
```
scope.init = function(){
            setTimeout(function () {
                calendar.fullCalendar(options);
            });
        };
```

**Comment by 32teeths** [comment]
I am having the same problem , but the calendar object is available in 

scope.$$childHead

And in the directive when i changed 
        scope.destroy = function(){
          if(attrs.calendar) {
            scope.calendar = scope.$parent.$parent[attrs.calendar] =  elm.html('');
          } else {
            scope.calendar = elm.html('');
          }
        }; 

I got what I wanted

**Comment by beeseenmedia** [comment]
In my case I injected uiCalendarConfig into the controller (not mentioned in documentation).  I see calendars.myCalendar inside, but fullCalendar is not.  I even tried the work around and it doesnt work.

All i see are the controllers but not the grid, if i click one of the buttons the grid gets rendered once I am inside the tab.  Angular UI Bootstrap

**Comment by antzo** [comment]
I have the same problem, all the events are fired but the callendar still not rendering.
This worked for me: (comment: options.calendars = null;)

```
function getOptions () {
    var calendarSettings = attrs.uiCalendar ? scope.$parent.$eval(attrs.uiCalendar) : {};
    var fullCalendarConfig = controller.getFullCalendarConfig(calendarSettings, uiCalendarConfig);
    var localeFullCalendarConfig = controller.getLocaleConfig(fullCalendarConfig);
    angular.extend(localeFullCalendarConfig, fullCalendarConfig);
                            options = {
                                eventSources : sources
                            };
                            angular.extend(options, localeFullCalendarConfig);
                            //remove calendars from options
                            //options.calendars = null;**

                            var options2 = {};
                            for (var o in options) {
                                if (o !== 'eventSources') {
                                    options2[o] = options[o];
                                }
                            }
                            return JSON.stringify(options2);
                        }
```
