### ISSUE TITLE
Start week on Monday

### ISSUE THREAD

**Issue by axanderlopez** [angular-ui/ui-calendar#282]
Is there any way to configure calendar week to start on Monday instead of Sunday?

**Comment by LilBiggs** [comment]
Yes. Take a look at the fullCalendar documentation [Here](http://fullcalendar.io/docs/display/firstDay/)

Example:

    $scope.uiConfig = {
        calendar:{
            firstDay:1,
            /* Other Properties */
        }
    }

**Comment by laander** [comment]
It may also be set implicitly by defining the language fullcalendar should work in, e.g.
```
$scope.uiConfig = {
    calendar: {
        lang: "da"
    }
}
```
See http://fullcalendar.io/docs/text/lang/

**Comment by asadmehboob** [comment]
how can we start week on select date(from date picker)??
