### ISSUE TITLE
Display aggregate information in the calendar 

### ISSUE THREAD

**Issue by sagar-ganatra** [angular-ui/ui-calendar#290]
Say the user has selected a view (Day, Week or Month). Is there a way to display the number of events in the given timeslot or the given day. For example, say there are 10 events from 10am - 11am or there are 10 events on 11th of July, then can this information be displayed.

**Comment by joshkurz** [comment]
This should be possible by altering calendar configurations. If its not then it is outside the scope of this directive. The directive is just a wrapper for the fullcalendar project, which is where the real meat and potatoes live.
