### ISSUE TITLE
Updating eventSources before server response results to duplicate entries

### ISSUE THREAD

**Issue by loykianos** [angular-ui/ui-calendar#298]
I have an application where the user can filter out appointments through a list of checkboxes.

Clicking on a checkbox changes the eventSources model, which fires a request to the server as intended, which is shown below. 
![calendar](https://cloud.githubusercontent.com/assets/4227423/8720333/612ed5f8-2bb2-11e5-9fd1-968e18b63b01.JPG)
 
The problem appears if somebody clicks a checkbox multiple times, without waiting for the response from the server. The result is the following.
![calendarmash](https://cloud.githubusercontent.com/assets/4227423/8720346/733e3ebe-2bb2-11e5-8b19-17fd914ed190.JPG)

Is there a way to fix this? If I had access to the request's promise, this wouldn't be a problem, but eventSources are handled in ui-calendar, which makes it hard to manage.

**Comment by joshkurz** [comment]
There are many different ways to fix this but it is more of a Model issue than a view issue. I am going to close this as a wont fix. You code allows the user to do this, which alters your model, which reflects in the  calendar. Just dont let your model get altered and the calendar will work correctly.
