### ISSUE TITLE
Changing time format

### ISSUE THREAD

**Issue by johneakin** [angular-ui/ui-calendar#301]
Hi,
Currently the calendar is showing the times as a prefix to the event names:
'1a test'
'2p test'

How can I reformat these to be
'01:00 test'
'14:00 test'

Thanks

**Comment by johneakin** [comment]
This seems to work

    $scope.uiConfig = {
        calendar: {
            timeFormat:'HH:mm'
                      }
                 }

**Comment by EsteBusta** [comment]
All the available configurations are listed in the http://fullcalendar.io/docs/ include that you mentioned.

**Comment by Sefriol** [comment]
@johneakin Nice that you found a solution! If you don't have any following issues with this topic, would you kindly close it? :)

Unintended Bioshock reference.
