### ISSUE TITLE
Demo not correct or calendar configuration passed wrong? 

### ISSUE THREAD

**Issue by apavlinovic** [angular-ui/ui-calendar#303]
Hi,

I've been trying to get the calendar to work, but the demo code is wrong...? Was there any breaking change that was not documented?

**Comment by kishorIntelligrape** [comment]
Hi ,

I am also facing problem with v1.0.0. It seems no custom configuration applies during initialization. Is there any change in the way we define config object.

**Comment by joshkurz** [comment]
yeah there was an issue with getting the config it should be fixed now.
