### ISSUE TITLE
Not working with Browserify as not published to npm

### ISSUE THREAD

**Issue by luchesar** [angular-ui/ui-calendar#304]
I wasn't able to npm install the library from npm.

If it's published to npm where can I find it and can you please add an example in the installation section?

**Comment by joshkurz** [comment]
its not published to npm currently. Going to close this for now. Please reopen if you really think we should publish to npm.

**Comment by martin-langhoff** [comment]
Please reopen (I cannot, probably only @luchesar and committers like @joshkurz can).

Fullcalendar is current on NPM as of v2.4.0 -- https://github.com/fullcalendar/fullcalendar/issues/2831

**Comment by luchesar** [comment]
"you cannot re-open your own issues if a repo collaborator closed them"

@joshkurz can you please reopen it?

**Comment by artemgrygor** [comment]
any updates here?
