### ISSUE TITLE
Two day event not displaying  

### ISSUE THREAD

**Issue by EsteBusta** [angular-ui/ui-calendar#321]
Hi, i'm setting an event from one day to next day(friday night 23:00 to saturday morning 06:00) 
{.....
     start = '2015-09-09T23:00:00',
     end =  '2015-09-10T06:00:00'
.....
};
But when the calendar loads the event, it just display the event in the first day(friday), i tried to change the timezone but still doesn't work.
The weird stuff here is that when the event "end" after 9 am it displays the event in both days(friday and saturday). 

Any advice?

**Comment by manish-bs** [comment]
Hi @EsteBusta , I am also facing the same issue. It would be great if you can let me know how did you fix it. Thanks.
