### ISSUE TITLE
How to add Resource view in UI-Calendar like arshaw fullcalendar resource view

### ISSUE THREAD

**Issue by anil017** [angular-ui/ui-calendar#36]
I Need to add resource view in our angular-ui calendar. I have found this link which has already implemented resource day view in arshaw fullcalendar using jQuery, but I am unable to integrate jQuery code to angular fullcalendar code.

https://github.com/ikelin/fullcalendar

So please give me some solution for this.

**Comment by funnybones** [comment]
How have you build & included that branch ?
