### ISSUE TITLE
Ui calendar

### ISSUE THREAD

**Issue by Jack113** [angular-ui/ui-calendar#376]
How can I browse to certain date ?  for example i have a button that shows data last year today, if  i click on it the calendar must go back one year

**Comment by flick36** [comment]
the ng-click of the button or however you are managing the click have to call a function in a controller where you inject the uiCalendarConfig and then just use it like:

    uiCalendarConfig.calendars.mycalendar..fullCalendar( 'gotoDate', date )

where date can be a Moment object, or anything the Moment constructor accepts.

http://fullcalendar.io/docs/current_date/gotoDate/
