### ISSUE TITLE
nowIndicator not supported

### ISSUE THREAD

**Issue by Hannibal42** [angular-ui/ui-calendar#378]
The full calendar has an option to display a red line at the current time, but this isnt working right now. 
http://fullcalendar.io/docs/current_date/nowIndicator/

**Comment by misterioss** [comment]
Why not? In my project (Meteor + Angular + Calendar UI) it work pretty well :)

**Comment by misterioss** [comment]
@Hannibal42 Why not? In my project (Meteor + Angular + Calendar UI) it work pretty well :)

**Comment by Hannibal42** [comment]
@misterioss I used it in the calendar config and had the calendar on the agendaWeek view but the Indicator didnt show. Can you maybe give me an example how you configured the calendar to show the indicator? :)

**Comment by flick36** [comment]
in your calendar config add `nowIndicator: true` that's all

**Comment by Hannibal42** [comment]
I used the wrong version -_-.
