### ISSUE TITLE
how to add custom clues in calendar per day

### ISSUE THREAD

**Issue by chenchen923** [angular-ui/ui-calendar#384]
I want to let per day only has two calendar events.When per day has more than two events,I want to add some prompts in per day,like:oh there has another events in this day.But i do not find how to do,please help me.

**Comment by peterver** [comment]
You can use the eventLimit option of fullCalendar

http://fullcalendar.io/docs/display/eventLimit/

Fullcalendar will automatically add a link titled 'show more' which will show a popup with the additional hidden events when pressed.

For Example, say you want to set the amount of events shown to 2, you simply do 

`
calendar : {
    views: {
        agenda : {
            eventLimit: 2,
        }
    }
}
`
