### ISSUE TITLE
Is Dead??

### ISSUE THREAD

**Issue by choiks14** [angular-ui/ui-calendar#388]
is dead project?

**Comment by martin-langhoff** [comment]
Yeah pretty much :-/ see #387

**Comment by shyamal890** [comment]
Was thinking about utilizing this library for a project. Now not so sure.

**Comment by martin-langhoff** [comment]
See #395 for news on maintainership. 

@shyamal890 -- although development has not been active, 

* it works very well in my experience
* I have material to prepare a bug fix release,
* It works well with the upcoming full calendar 2.7.0, a highly expected release as it will have support for drag-and-drop on touch screen devices
* see #395 , come join us lend a hand

**Comment by martin-langhoff** [comment]
No it's not :-)
