### ISSUE TITLE
How to hide time in week view?

### ISSUE THREAD

**Issue by tirumalavasu** [angular-ui/ui-calendar#389]
Hi, I am using it in my project. I don't want to show time in week view, could anyone help me? I want to hide those time cells in a day, i just want to show one cell per each day.

![ui](https://cloud.githubusercontent.com/assets/3540345/13813071/74b07d9e-eba5-11e5-8997-408073b68522.PNG)

**Comment by flick36** [comment]
http://fullcalendar.io/docs/views/Available_Views/

The one you are lookin is **basicWeek** - [see example](http://fullcalendar.io/views/basicWeek/)
