### ISSUE TITLE
Integrate upcoming FullCalendar 2.7 with Touch support

### ISSUE THREAD

**Issue by martin-langhoff** [angular-ui/ui-calendar#394]
I am working on an early integration with the beta for 2.7. See http://fullcalendar.io/blog/2016/03/touch-support/

**Comment by flick36** [comment]
This [library](http://touchpunch.furf.com/) it's all you need

**Comment by martin-langhoff** [comment]
Yeah, I meant testing, validating FC 2.7 with latest release of ui-calendar, fixing any issues if needed, updating docs (for example, to point to TouchPunch).

As it turns out, I think ui-calendar will just work. I am beta testing a webapp with it and no bugs so far.

**Comment by flick36** [comment]
Yesso far  it works out of the box

**Comment by martin-langhoff** [comment]
#408 closes this issue formally, please provide feedback on how current master works for you on #408.
