### ISSUE TITLE
Full Calendar is not displayed at the beginning.

### ISSUE THREAD

**Issue by Nextt1** [angular-ui/ui-calendar#397]
![untitled-error](https://cloud.githubusercontent.com/assets/7522749/14277985/24874a20-fb43-11e5-86b5-2868f55f78ae.png)
I am using angular-material design library. Now in a specific view I am trying to load full-calendar but it not displayed at first. As soon as I click any header buttons the calendar will be displayed as desired. but I want to display as soon as I change to this view. Here is my View file 

    <md-content layout="column" layout-align="center center">
       <div ui-calendar="uiConfig.calendar" ng-model="eventSources">
       </div>
     </md-content>  

Controller File

     $scope.eventSources = [];

    $scope.uiConfig = {
        calendar:{
            height: 560,
            defaultView: 'basicWeek ',
            header:{
                left: 'month agendaWeek agendaDay',
                center: 'title',
                right: 'today prev,next'
            }
    }
    };

I am not getting any error on my console.

**Comment by flick36** [comment]
Did you manage to solve this? i'm having the same issue

**Comment by martin-langhoff** [comment]
FC might not be entirely happy with some modes of show/hide. Some folks have hit issues with FC nested inside an 'accordion'. Google for that and perhaps one of the workarounds works for you :-)

**Comment by flick36** [comment]
Thing is i have the calendar in the index, and won't render either.... until i press the buttons.

**Comment by flick36** [comment]
I've managed to get it working by adding a timeout function in the code in line 257 insted of

`calendar.fullCalendar(options);`

I've changed it to:

    setTimeout(function () {
        calendar.fullCalendar(options);
    });

**Comment by Nextt1** [comment]
Thanks for the answer. It is working for me now.

**Comment by Ric17101** [comment]
@flick36 , may I know sir what would be the value of options as parameter on .fullCalendar? Thanks!

**Comment by alexismansilla** [comment]
Thank! for workaround @flick36 it is working for me.
