### ISSUE TITLE
jsEvent in eventDrop

### ISSUE THREAD

**Issue by arrabal** [angular-ui/ui-calendar#406]
I need to get some information about the drop event, but when I examine jsEvent parameter in eventDrop event, it contains the boolean value false 

```
...
eventDrop: $scope.alertOnDrop,
...
$scope.alertOnDrop = function(event, delta, revertFunc, jsEvent, ui, view){
     console.info('jsEvent: ', jsEvent);    
};
```

In other events, such as eventClick or eventMouseover, jsEvent is not a boolean, but it is an object with many fields. Is this situation normal?

**Comment by martin-langhoff** [comment]
use the drop events from FullCalendar :-)
