### ISSUE TITLE
Drag functionality is not working in chrome

### ISSUE THREAD

**Issue by kmeado** [angular-ui/ui-calendar#407]
The demo site https://angular-ui.github.io/ui-calendar/ works fine however when implementing the code (exactly as the demo is) into my project the drag functionality fails in chrome. Drag does work in opera, safari, firefox, edge and ie though ... Im not sure how to approach this

**Comment by martin-langhoff** [comment]
In general, this works for me :-)

Find the difference between the demo and your code. That's what I do when something works on the demo site but isn't working in my app.  Not easy, I know.

Note that, in my experience, the Chrome desktop browser has a "tablet" mode for testing but it does not emulate touch.

**Comment by kmeado** [comment]
Actually I found the issue. My laptop is a touch screen and for some reason chrome gets confused on my site. If I disable touch events through chrome://flags then it works perfect (minus the touch capability) not sure why chrome is screwing this up as it works fine with touch or click on the demo site ...?

**Comment by martin-langhoff** [comment]
Using vs not using touchpunch might be interesting to test. 

In any case, closing this issue.
