### ISSUE TITLE
Calendar initialization can fail if no lang is configured for calendar config.

### ISSUE THREAD

**Issue by rizoom** [angular-ui/ui-calendar#416]
[Seems new to 2.7.1 (last commit)](https://github.com/angular-ui/ui-calendar/pull/408/commits/cec039725f4e761bfb5e20cea2e7f2bddf03d57a)
See PR #415

**Comment by l6gslayer** [comment]
I can confirm this is happening. I received a "TypeError: Cannot read property '5' of undefined" if I do not include a language in the configuration object.  As soon as I include the language property, the calendar loads as normal.

Angular: 1.5.5
FullCalendar: 2.7.2
Jquery: 2.1.4
Moment: 2.13.0
Chrome: Version 50.0.2661.102 m

![image](https://cloud.githubusercontent.com/assets/3011314/15752042/32341636-28a1-11e6-8100-94c5ec859282.png)

**Comment by peterver** [comment]
i'll take a look at it tomorrow :]

**Comment by rizoom** [comment]
Any feedback? A PR is already provided, it is an tiny merge, really easy ;)

**Comment by martin-langhoff** [comment]
Thank you!
