### ISSUE TITLE
The demo is not keeping added items on the calendar when switching between months

### ISSUE THREAD

**Issue by michplunkett** [angular-ui/ui-calendar#417]
URL: http://angular-ui.github.io/ui-calendar/

Recreation steps (All done in the 'month' view):
1. Click on the 'Add Event' button
2. Look and confirm that the event 'Open Sesame' is added
3. Forward a month (May -> June)
4. Go back a month (June -> May)
5. You will see that the 'Open Sesame' event is now missing from the calendar in the spot you added it. It will be on the side of the calendar, but not displayed in the calendar.
![step 0](https://cloud.githubusercontent.com/assets/5885605/15689915/b4445886-2746-11e6-82ac-0a8cdc344b60.png)
![step 1 and 2](https://cloud.githubusercontent.com/assets/5885605/15689917/b449afd4-2746-11e6-8c37-1ff7c127b04d.png)
![step 3](https://cloud.githubusercontent.com/assets/5885605/15689916/b4464880-2746-11e6-9254-208e99e6f01d.png)
![step 4 and 5](https://cloud.githubusercontent.com/assets/5885605/15689914/b443e784-2746-11e6-91af-7ca857920bec.png)

**Comment by michplunkett** [comment]
I am experiencing the same thing when I tried it in my application, but this is the best example I could quickly mock up.

**Comment by martin-langhoff** [comment]
Look for 'sticky' in the README. It's a FAQ :-)

**Comment by michplunkett** [comment]
Found it, thanks!

**Comment by karthiksekarnz** [comment]
@martin-langhoff Dude you are a life saver! it worked, I spent a day trying to fix this, I thought I had some issues with my scope variables
