### ISSUE TITLE
bower ECONFLICT

### ISSUE THREAD

**Issue by fventurini** [angular-ui/ui-calendar#427]
problem installing with bower
suggestions?

`"C:\Users\user\AppData\Roaming\npm\bower.cmd" "install" "--save" "angular-ui-calendar#1.0.1"
bower angular-ui-calendar#1.0.1 cached https://github.com/angular-ui/ui-calendar.git#1.0.1
bower angular-ui-calendar#1.0.1         validate 1.0.1 against https://github.com/angular-ui/ui-calendar.git#1.0.1
bower angular-ui-router#^0.2.18           cached https://github.com/angular-ui/angular-ui-router-bower.git#0.2.18
bower angular-ui-router#^0.2.18         validate 0.2.18 against https://github.com/angular-ui/angular-ui-router-bower.git#^0.2.18
bower angular#1.3.15                      cached https://github.com/angular/bower-angular.git#1.3.15
bower angular#1.3.15                    validate 1.3.15 against https://github.com/angular/bower-angular.git#1.3.15
bower moment#2.*                          cached https://github.com/moment/moment.git#2.14.1
bower moment#2.*                        validate 2.14.1 against https://github.com/moment/moment.git#2.*
bower fullcalendar#2.3.1                  cached https://github.com/fullcalendar/fullcalendar.git#2.3.1
bower fullcalendar#2.3.1                validate 2.3.1 against https://github.com/fullcalendar/fullcalendar.git#2.3.1
bower angular#^1.x                        cached https://github.com/angular/bower-angular.git#1.5.7
bower angular#^1.x                      validate 1.5.7 against https://github.com/angular/bower-angular.git#^1.x
bower angular#^1.4.8                      cached https://github.com/angular/bower-angular.git#1.5.7
bower angular#^1.4.8                    validate 1.5.7 against https://github.com/angular/bower-angular.git#^1.4.8
bower angular#^1.0.0                      cached https://github.com/angular/bower-angular.git#1.5.7
bower angular#^1.0.0                    validate 1.5.7 against https://github.com/angular/bower-angular.git#^1.0.0
bower angular#1.5.7                       cached https://github.com/angular/bower-angular.git#1.5.7
bower angular#1.5.7                     validate 1.5.7 against https://github.com/angular/bower-angular.git#1.5.7
bower                                  ECONFLICT Unable to find suitable version for angular`

**Comment by peterver** [comment]
it appears your bower file doest have a resolution for which angular version it should use. Since you're using angular 1.5.7 and ui-calendar has its dependency set on 1.4.x as of this writing, this might be the issue.

I'm personally running on 1.5.x so it shouldnt be an issue to resolve to 1.5.x in your bower file :], add the following to your bower.json

`
"resolutions": {
  "angular": "1.5.7"
}
`

**Comment by cdupoiron** [comment]
+1

**Comment by leolion75** [comment]
This help me, thanks.
