### ISSUE TITLE
Moment Version Change in bower.json

### ISSUE THREAD

**Issue by BrandonEMiller** [angular-ui/ui-calendar#432]
In the prior release of 1.0.1 the bower.json for this project was set to moment 2.*, which led to a moment 2.11.x version.  In the release of 1.0.2, this version became locked to a lower minor of moment in the 2.10.x version.  

Prior to yesterday we were working with moment 2.11.x from the previous bower requirement and had built up other dependencies on the later version of moment, so this has caused a few conflicts. Was there a reason that this is set to an old minor version or can it be bumped to 2.11.x?

**Comment by peterver** [comment]
No apparent reason to be honest, full calendar itself has it set to >= 2.5.0, so the 2.* in the ui-calendar repo was not really good.

Question on the side, is it ok if i set it to >= 2.5.0 ( this way it is the same as with the original full calendar repo ) ?

**Comment by peterver** [comment]
should be fixed as  of : #433
