### ISSUE TITLE
Upgrade Angular dependency to 1.5.X

### ISSUE THREAD

**Issue by spiresd55** [angular-ui/ui-calendar#444]
Maybe I could create a Pull Request for this, but is it possible to make this library work with the latest version of Angular 1? Preferably 1.5.X and above?

**Comment by peterver** [comment]
to be honest i wouldnt really do this, becuase of the fact that there's most likely a couple applications dependent on 1.4 that dont have the resources or manpower internally to make the move to 1.5.x, what would be acceptable however is to define it as 1.4 and up ? this would allow anyone willing to use a more recent version of angular, to do so. It would only require them to set the version in their bower file ( and potentially a resolution if needed ).

Could you create a pull request for that ?

Thanks in advance !

**Comment by peterver** [comment]
i just saw that you did ! Tested and merged :] +1 !

**Comment by IShm** [comment]
@peterver, the latest available version in bower is 1.0.2. It doesn't contain this fix.
Is it possible to update/release new version on bower?
