### ISSUE TITLE
Full Calendar 2.7.1 not compatible with jQuery 3

### ISSUE THREAD

**Issue by lluiscanals** [angular-ui/ui-calendar#450]
Hi, 

Full Calendar 2.8 was released in order to be compatible with JQuery 3. You can see here

https://github.com/fullcalendar/fullcalendar/issues/3124

Now full calendar is in v. 3.0.0
Can ui-calendar update the dependency with full calendar at least to 2.8?

Thanks and regards,
    Lluís

**Comment by tkarls** [comment]
+1
Time to update Full Calendar version

**Comment by valenburm** [comment]
+1
Fully agree

**Comment by CJBrew** [comment]
There's a bug in the way JQ works with FullCalendar that's been fixed in the FC 3.0.0.
 https://github.com/fullcalendar/fullcalendar/issues/3357

**Comment by shyamal890** [comment]
+1

**Comment by mohamed-magdy** [comment]
+1

**Comment by paulsperanza** [comment]
+1

**Comment by zachdunn** [comment]
Submitted a PR to updated here: https://github.com/angular-ui/ui-calendar/issues/472
