### ISSUE TITLE
Refresh event on next or prev button  urgent!!

### ISSUE THREAD

**Issue by baderkhane** [angular-ui/ui-calendar#463]
Hello guys,
Please i need a help, im working with FullCalendar in ionic project, im getting events from local database (sqlite), in the first use all is going well but when im clicking Next or Prev button my events disappearing.

Thanks in advance

**Comment by martin-langhoff** [comment]
Search in the docs for `stick` :-)

**Comment by baderkhane** [comment]
Thanks you saved my life 👍
