### ISSUE TITLE
events rendering is very slow on IE11

### ISSUE THREAD

**Issue by nazrul074** [angular-ui/ui-calendar#488]
Hi,
I am trying to load about 55 events in the ui-calendar. In Chrome, performance is slow but acceptable but IE11 it is terrible.  Then I have checked IE UI-Responsiveness and found only DOM event load by angular is taking 9.53 seconds.
![ie-ui-responsiveness](https://cloud.githubusercontent.com/assets/7368712/23727159/ea54c166-0424-11e7-972c-b4038c52cf59.PNG)
`	self.calendarConfig = {
		height: 600,
		header: {
			left: '',
			center: '',
			right: ''

		},
		defaultView: 'month',
		firstHour: 8,
		eventLimit: true,
		editable: false,
		eventClick: function (calEvent, jsEvent, view) {
			--here i am rendering a popup			
		},
	};
	self.calendar = angular.element('#calendar');
	self.eventSources = [self.events];`
I am using custom header and previous, next buttons they are working file. I have seen database call is only taking around 0.3seconds. Please help me to resolve the issue.

**Comment by nazrul074** [comment]
found the solution rather than setting eventSources directly adding the eventSources to fullCalendar worked. 
	self.calendar.fullCalendar('addEventSource', self.events);

**Comment by Sujay-shetty** [comment]
@nazrul074 
I'm also facing performance issue with ui-calendar.

Loading the events in 'addEventSource' method only. but in calendar per day there are 500 events in month view. Performance vice it is taking more time.
$('#calendarView').fullCalendar('removeEventSource', $scope.events);
Do you have any suggestions on the same.

Thanks,
Sujay

**Comment by nazrul074** [comment]
If you want to remove all the events then you can use 
`.fullCalendar('removeEvents')`
also you can remove list of events. Check this link : https://fullcalendar.io/docs/removeEvents

Thanks,
Nazrul

**Comment by Sujay-shetty** [comment]
Tried removeEvents as well but no luck.
There are 500(events)*30(days) = 15000 events has to render in month view. Due to which loading time is very high.

Thanks,
Sujay
