### ISSUE TITLE
How to retrieve an object dropped on the ui-calendar

### ISSUE THREAD

**Issue by mehdiloup** [angular-ui/ui-calendar#87]
/**\* RELATED QUESTION #43 ***/

Hi everyone,

Arshaw full-calendar offers the possibility to drop objects on the calendar. It is simple to retrieve the dropped element with the keyword this  (http://arshaw.com/fullcalendar/docs/dropping/drop/)

Unfortunately, the keyword this in the $scope.uiConfig refers to window object as the ui-calendar is an angular directive.

Could anyone help figure out how to retrieve a dropped object in drop function of the $scope.uiConfig 

Thank you!

Mehdi-Loup

**Comment by andrew-burgess-motasoft** [comment]
Has anyone managed to get this working with https://github.com/codef0rmer/angular-dragdrop? I can't get it to hit **mutatedraggable** at any point, and I'm guessing because of that, it's not hitting **uiConfig.calendar.drop**. @mehdiloup ?
