### ISSUE TITLE
Event disappear after switching months

### ISSUE THREAD

**Issue by fantasyzhw** [angular-ui/ui-calendar#99]
I was using this ui-calendar and found a issue that the event will disappear after switching to different months. The same issue happens on the demo here
http://angular-ui.github.io/ui-calendar/

delete some existing event -> add new event -> move the event to a different date -> go to next month -> go back to the current month
Then the new event will disappear. Note that the event is still on the list but just not on the calendar. I have tracked the behavior in the js console, and the source is still correct, but if I do $('#Calendar').fullCalendar( 'clientEvents' ); it does not show up that newly created event.

![screen shot 2014-04-11 at 3 37 42 pm](https://cloud.githubusercontent.com/assets/7268200/2685426/6999b3e6-c1ca-11e3-908d-78c92c199e61.png)
![screen shot 2014-04-11 at 3 37 54 pm](https://cloud.githubusercontent.com/assets/7268200/2685428/6999c3f4-c1ca-11e3-92f5-e003ee56993f.png)
![screen shot 2014-04-11 at 3 38 09 pm](https://cloud.githubusercontent.com/assets/7268200/2685427/6999bfa8-c1ca-11e3-8188-d0c3913ded49.png)
![screen shot 2014-04-11 at 3 38 03 pm](https://cloud.githubusercontent.com/assets/7268200/2685429/699a171e-c1ca-11e3-98f3-0cad382a7feb.png)

**Comment by ppdg** [comment]
@linkolen Thanks :)

**Comment by tony75** [comment]
Same problem for me with fullcalendar 2.2.6 and latest angular ui calendar

**Comment by anphu7492** [comment]
Hi, I got this problem and then I modified the onAdded function as @linkolen suggested. It worked, but then I realized that when I dragged and dropped the events, I got this error: TypeError: Converting circular structure to JSON and I noticed that the event object has the "source" attribute which makes the event object have circular structure. Does anybody have the same issue? Or can you suggest a solution for this?

**Comment by cupito** [comment]
Why not to modify adding events? I added the attribute ```stick: bool``` to my events and changed the 

``` javascript
eventsWatcher.onAdded = function(event) {
    scope.calendar.fullCalendar('renderEvent', event, event.stick ? event.stick : false);
};

$scope.events.push({ title: 'name', start:'2015-01-01', stick: true});
```

**Comment by Dlsqueak** [comment]
@anphu7492 I'm getting the same issue with the TypeError using @linkolen suggesting. In fact if I go in to modify the date object at all (i.e. increment the hour) I get that error. Still looking into a fix, either for the original issue that doesn't lead to this error, or a way around this.

**Comment by anphu7492** [comment]
Hi @Dlsqueak , Thank you for your suggestion. I also did the same thing. Actually, I deleted the 'source' property whenever I have to do something with the server. :D

**Comment by jstoddardiv** [comment]
@linkolen Your solution works awesome for me. Thanks! (FullCalendar v2.1.1)

**Comment by linkolen** [comment]
you are welcome @jstoddardiv

**Comment by erickne** [comment]
@linkolen thanks dude!

**Comment by angelix** [comment]
If you add the event with the stick flag true then the event will stick to the calendar.
CAUTION: The minified version is not working properly. Use the src/calendar.js

```javascript

var event = {
			title : $scope.newSchedule.expertise.toUpperCase().replace('-','_'),
			start : date,
			end : moment(date).add($scope.newSchedule.duration | 0 , "minutes").toDate(),
			stick : true, 
			// expertise : $scope.newSchedule.expertise,
			// type : $scope.newSchedule.type,
			// repeat : $scope.newSchedule.repeat,
		};
```

**Comment by laving1977** [comment]
Still don't get it working properly. Is there a one complete fix on this issue?

**Comment by ggondim** [comment]
The stick property worked for me. Maybe this issue can be closed.

**Comment by actuallymab** [comment]
.```
fullCalendar( 'renderEvent', event [, stick ] )
```

setting ```stick``` to true, is solved my problem

**Comment by ramang16** [comment]
I am using fullcalendar 2.4.0, latest ui-calendar available in https://github.com/angular-ui/ui-calendar/blob/master/src/calendar.js.

I am fetching new events on clicking next/previous and adding to the $scope.events. I have this logic in  events: function( start, end, callback ) {}, whenever there is change in month, based on some condition, I am pulling the new events.

I used stick: true in the event before adding to $scope.events, still events are gone after changing month.

Any help would be appreciated.

Thanks

**Comment by kelvinlogic** [comment]
The calender is supposed to load monthly events. notice the event persist when switching between different days and weeks within the same month.

**Comment by maffelbaffel** [comment]
stick solved my problem too.

**Comment by martin-langhoff** [comment]
This is a bit of a FAQ of FC itself. Set event to stick. FC author explains his rationale on #353 .

**Comment by ovarunendra** [comment]
stick as true solved my problem too.

**Comment by olefrank** [comment]
Thanks @angelix and @linkolen. Both suggestions works. I prefer the one by angelix.

**Comment by MaxKolle** [comment]
@linkolen  thanks... worked for me too

**Comment by voloKh28** [comment]
When you paste `stick: true` to your event object you also need to add option when call `renderEvent`

`$(fullCalendar).fullCalendar('renderEvent', event, true);`

**Comment by jebberwocky** [comment]
when using dow and stick together it causes duplicated events

**Comment by nikollaih** [comment]
> Hi joshkurz, I've try to reproduce this behavior directly in fullCalendar to open an official issue.
> I've create a JSFiddle you can see here: http://jsfiddle.net/vanHuntsman/KzADf/1/
> If we add events with 'stick' property as undefined, as documentation says, those events disappear when the calendar refetches.
> 
> Why do you think is an issue with the fullcalendar library itself?
> Should not the eventsWatcher.onAdded() set the stick property to true?
> What I don't really get is why when eventsWatcher.onAdded() calls renderEvent with 'stick' undefined the events are 'sticky' (what is the opposite the doc says).
> 
> In fact, if instead of adding the event to the array that is being watched by the eventsWatcher I call
> 
> ```
> $('#myCalendar').fullCalendar('renderEvent', myEvent, true);
> ```
> Then it works good.

$('#myCalendar').fullCalendar('renderEvent', myEvent, true); this work for me, thank you

**Comment by syamprasadreddy** [comment]
> just go to your calendar.js and change onAdded
> eventsWatcher.onAdded = function(event) {
> scope.calendar.fullCalendar('renderEvent', event,true);
> };
> Work's for me 👍

yes thanks a lot u gave me correct solution

**Comment by Hasan-Mainul** [comment]
$scope.getAllTimelineByPOID = function (PurchaseOrderID) {
        timelineService.getAllTimelineByPOID(PurchaseOrderID).then(function (res) {
            if (res.data.length > 0) {
                $scope.timelineList = formatDate(res.data, '', ["PlannedDate", 'ActualDate', 'LastModified']);      
                var calenderval = res.data;
                //Cache= true;
                angular.forEach(calenderval, /*stick,*/ function (value) {                  
                    $scope.events.push({
                        title: value.Description,
                        start: value.ActualDate
                        //Cache: true
                        //stick: true
                        //end: value.ActualDate,
                        //allDay: false

                    });
                });
                $scope.eventSources = [$scope.events];
                console.log($scope.eventSources);

                for (var i = 0; i < $scope.timelineList.length; i++) {
                    $scope.timelineList[i].ActualDate = new Date($scope.timelineList[i].ActualDate);
                    $scope.timelineList[i].LastModified = new Date($scope.timelineList[i].LastModified);
                }
            }
            else {
                $scope.timelineList.push($scope.timeline);
            }
        });
    }; 

i'm facing same problem , help me out
After switching month or after hitting today icon event date disappear

**Comment by Hasan-Mainul** [comment]
> Still don't get it working properly. Is there a one complete fix on this issue?

i'm also looking for it
